
	// CONVERTE O TEXTO EM HEXADECIMAL PARA O FORMATO HEXPIC E O PRINTA NO ELEMENTO CANVAS

	function HexPic(hex){

		if (hex != ''){
			var campo_texto = document.querySelector("#texto");
			var campo_resul = document.querySelector("#resultado");

			if (!campo_texto.classList.contains("oculto")) {
				campo_texto.classList.add("oculto");
				campo_resul.classList.remove("oculto");
			}

			var hex_tam = hex.length;
			var cluster = Math.ceil(hex_tam / 6);

			if ((hex_tam / 6) != cluster) {
				switch ((cluster * 6) - hex_tam) {
		  			case 0:
		  				break;
		  			case 1:
		  				hex = hex + '0';
		  				break;
					case 2:
						hex = hex + '00';
						break;
					case 3:
						hex = hex + '000';
						break;
					case 4:
						hex = hex + '0000';
						break;
					case 5:
						hex = hex + '00000';
						break;
				}
			}

			console.log(hex+ ' / ' + hex_tam + ' hexs e ' + cluster + ' clusters');

			tela = Math.sqrt(cluster);
			tela_ar = Math.ceil(tela);

			canvas.width  = tela_ar;
			canvas.height = tela_ar;
			canvas.style.background = "#000";

			var x = 0;
			var y = 0;

			for (var i = 0; i < hex_tam; i = i + 6) {
				drawPixel(x, y, '#' + hex.substr(i, 6));
				if (x == tela_ar - 1){
					x = 0;
					y++;
				} else {
					x++;
				}
			}

			// CRIA O RESULTADO VISIVEL

			var img = canvas.toDataURL("image/png");
			document.getElementById("tela_resultado").src = img;
			document.getElementById("salvar_hexpic").href = img;
			document.getElementById("legenda").innerHTML = '<b>' + geraLegenda(24) + '</b> generated by HexPic';

			//CRIA UM HEXPIC EXTENDIDO

			canvas_b.width  = 1080;
			canvas_b.height = 1080;

			context_b.beginPath();
			context_b.rect(0, 0, 1080, 1080);
			context_b.closePath();
			context_b.fillStyle = "#000";
			context_b.fill();

			context_b.imageSmoothingEnabled = false;

			context_b.drawImage(canvas, 0, 0, 1080, 1080);

			var img_ext = canvas_b.toDataURL("image/png");
			document.getElementById("salvar_hexpic_ext").href = img_ext;

		}

	}

	// INVOCA AS FUNÇÕES PARA CONVERTER O TEXTO UTF-8 PARA HEXADECIMAL

	function Hex(textoUTF){
		hex = obterHex(obterUTF8(textoUTF));
		return hex;
	}
	
	// DESENHA PIXEL COM BASE NA COORDENADA X E Y, USANDO A COR HEXA DESIGNADA

	function drawPixel(x, y, color) {
		var roundedX = Math.round(x);
		var roundedY = Math.round(y);
	    context.beginPath();
	    context.fillStyle = color || '#000';
	  	context.fillRect(roundedX, roundedY, 1, 1);
	    context.fill();
	}


	// CONVERSOR UTF-8 PARA HEXADECIMAL

	function obterHex(bytes) {
	  return Array.from(bytes, byte => byte.toString(16).padStart(2, "0")).join("");
	}

	function obterUTF8(string) {
	  return new TextEncoder().encode(string);
	}

	function salvarHexPic(){
		var dataURL = canvas.toDataURL("image/png");
		var newTab = window.open('about:blank','image from canvas');
		newTab.document.write("<img src='" + dataURL + "' alt='from canvas'/>");
	}

	function geraLegenda(tamanho){
		var legenda = document.getElementById("texto").value;

		if (legenda.length > tamanho){
			legenda = legenda.substr(0, tamanho) + '...';
		}

		return legenda;
	}

	function geraCor(){
		var gerar1 = document.querySelector("#gerar1");
		var gerar2 = document.querySelector("#gerar2");

		gerar1.classList.add("oculto");
		gerar2.classList.remove("oculto");

	}

	function geraArte(){

		// CRIA UM CANVAS NOVO EM FORMATO DE QUADRO

		var arte_pronta = document.getElementById("arte_pronta");
		var arte_context = arte_pronta.getContext("2d");

		var altura_total = 1080;
		var largura_total = 1920;
		var quadro = 920;
		var margem = 80;
		var preenc = 65;
		var moldura = 40;

		arte_pronta.width  = largura_total;
		arte_pronta.height = altura_total;

		// DESENHANDO O QUADRO E A SOMBRA

		arte_context.filter = 'none';
		arte_context.beginPath();
		arte_context.rect(0, 0, largura_total, altura_total);
		arte_context.fillStyle = '#f5f5f5';
		arte_context.closePath();
		arte_context.fill();
		

		arte_context.filter = 'blur(4px)';
		arte_context.beginPath();
		arte_context.rect(margem+4, margem+4, quadro, quadro);
		arte_context.fillStyle = '#8F8F8F';
		arte_context.closePath();
		arte_context.fill();
		arte_context.filter = 'none';

		// DESENHANDO A BORDA RIGDE

		arte_context.beginPath();
		arte_context.moveTo(margem, margem);
		arte_context.lineTo(margem, margem+quadro);
		arte_context.lineTo(margem+quadro, margem);
		arte_context.closePath();
		arte_context.fillStyle = "#3c493f";
		arte_context.fill();


		arte_context.beginPath();
		arte_context.moveTo(margem+(moldura/2), margem+(moldura/2));
		arte_context.lineTo(margem+(moldura/2), margem+quadro-(moldura/2));
		arte_context.lineTo(margem+quadro-(moldura/2), margem+(moldura/2));
		arte_context.closePath();
		arte_context.fillStyle = "#28312a";
		arte_context.fill();

		arte_context.beginPath();
		arte_context.moveTo(margem, margem+quadro);
		arte_context.lineTo(margem+quadro, margem+quadro);
		arte_context.lineTo(margem+quadro, margem);
		arte_context.closePath();
		arte_context.fillStyle = "#28312a";
		arte_context.fill();

		arte_context.beginPath();
		arte_context.moveTo(margem+(moldura/2), margem+quadro-(moldura/2));
		arte_context.lineTo(margem+quadro-(moldura/2), margem+quadro-(moldura/2));
		arte_context.lineTo(margem+quadro-(moldura/2), margem+(moldura/2));
		arte_context.closePath();
		arte_context.fillStyle = "#3c493f";
		arte_context.fill();

		// DESENHA O CAMPO BRANCO

		arte_context.beginPath();
		arte_context.rect(margem+moldura, margem+moldura, quadro-(moldura*2), quadro-(moldura*2));
		arte_context.closePath();
		arte_context.fillStyle = "#FFF";
		arte_context.fill();

		arte_context.imageSmoothingEnabled = false;

		arte_context.drawImage(document.getElementById("tela_resultado"), margem+moldura+preenc, margem+moldura+preenc, quadro-(2*(moldura+preenc)), quadro-(2*(moldura+preenc)));

	    arte_context.font = "10px Merriweather";
		arte_context.fillStyle = "#CCC";
		arte_context.textAlign = 'right';
		arte_context.fillText(geraLegenda(24) + ' - by HexPic ', quadro+margem-preenc-moldura+3, quadro+margem-preenc-moldura+12);


		// DESENHA LOGO DO HEXPIC

		arte_context.beginPath();
		arte_context.rect(largura_total-margem-128, margem, 128, 128);
		arte_context.closePath();
		arte_context.fillStyle = "#486578";
		arte_context.fill();

		arte_context.beginPath();
		arte_context.rect(largura_total-margem-64, margem, 64, 64);
		arte_context.closePath();
		arte_context.fillStyle = "#506963";
		arte_context.fill();

		arte_context.beginPath();
		arte_context.rect(largura_total-margem-128, margem+64, 64, 64);
		arte_context.closePath();
		arte_context.fillStyle = "#5f2e70";
		arte_context.fill();

		arte_context.beginPath();
		arte_context.rect(largura_total-margem-64, margem+64, 64, 64);
		arte_context.closePath();
		arte_context.fillStyle = "#726f6a";
		arte_context.fill();

		arte_context.font = "25px Merriweather";
		arte_context.fillStyle = "#666";
		arte_context.textAlign = 'right';
		arte_context.fillText(geraLegenda(30), largura_total-margem, altura_total-margem);

		var img = arte_pronta.toDataURL("image/png");
		document.getElementById("salvar_arte").href = img;

	}